# LAB Text Generation with Neural Networks

## Functions for Processing Text

### Reading in files as a string text

In [1]:
def read_file(filepath):
    
    with open(filepath) as f:
        str_text = f.read()
    
    return str_text

#### Call the function below and read teh file: moby_dick_four_chapters.txt

In [2]:
read_file('moby_dick_four_chapters.txt')

'Call me Ishmael.  Some years ago--never mind how long\nprecisely--having little or no money in my purse, and nothing\nparticular to interest me on shore, I thought I would sail about a\nlittle and see the watery part of the world.  It is a way I have of\ndriving off the spleen and regulating the circulation.  Whenever I\nfind myself growing grim about the mouth; whenever it is a damp,\ndrizzly November in my soul; whenever I find myself involuntarily\npausing before coffin warehouses, and bringing up the rear of every\nfuneral I meet; and especially whenever my hypos get such an upper\nhand of me, that it requires a strong moral principle to prevent me\nfrom deliberately stepping into the street, and methodically knocking\npeople\'s hats off--then, I account it high time to get to sea as soon\nas I can.  This is my substitute for pistol and ball.  With a\nphilosophical flourish Cato throws himself upon his sword; I quietly\ntake to the ship.  There is nothing surprising in this.  If t

#### import spacy

In [3]:
import spacy

#### load: en_core_web_sm and assign it to a variable call "nlp"

In [11]:
nlp = spacy.load('en_core_web_sm')

#### Let's calculate the length

In [12]:
nlp.max_length = 1198623

#### create a function to separate punctuation

In [13]:
def separate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']

In [7]:
#### call the function read_file and read the file: melville-moby_dick.txt and save it in a variable called "d"

In [14]:
d = read_file('melville-moby_dick.txt')

In [9]:
#### using a variable called tokens, call the separate_punc function. Send "d" as a parameter

In [15]:
tokens = separate_punc(d)

#### List the tokens

In [16]:
tokens

['chapter',
 '1',
 'loomings',
 'call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on',
 'shore',
 'i',
 'thought',
 'i',
 'would',
 'sail',
 'about',
 'a',
 'little',
 'and',
 'see',
 'the',
 'watery',
 'part',
 'of',
 'the',
 'world',
 'it',
 'is',
 'a',
 'way',
 'i',
 'have',
 'of',
 'driving',
 'off',
 'the',
 'spleen',
 'and',
 'regulating',
 'the',
 'circulation',
 'whenever',
 'i',
 'find',
 'myself',
 'growing',
 'grim',
 'about',
 'the',
 'mouth',
 'whenever',
 'it',
 'is',
 'a',
 'damp',
 'drizzly',
 'november',
 'in',
 'my',
 'soul',
 'whenever',
 'i',
 'find',
 'myself',
 'involuntarily',
 'pausing',
 'before',
 'coffin',
 'warehouses',
 'and',
 'bringing',
 'up',
 'the',
 'rear',
 'of',
 'every',
 'funeral',
 'i',
 'meet',
 'and',
 'especially',
 'whenever',
 'my',
 'hypos',
 'get',
 'such

#### Get the lenght of tokens

In [17]:
len(tokens)

214708

In [18]:
4431/25

177.24

## Create Sequences of Tokens

In [19]:
# organize into sequences of tokens
train_len = 25+1 # 50 training words , then one target word

# Empty list of sequences
text_sequences = []

for i in range(train_len, len(tokens)):
    
    # Grab train_len# amount of characters
    seq = tokens[i-train_len:i]
    
    # Add to list of sequences
    text_sequences.append(seq)

#### using ' '.join() display the words of the first sequence [0]

In [20]:
' '.join(text_sequences[0])

'chapter 1 loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to'

#### display the words of the second sequence [1]

In [21]:
' '.join(text_sequences[1])

'1 loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest'

#### display the words of the third one

In [22]:
' '.join(text_sequences[2])

'loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me'

#### get the length of text_sequences

In [23]:
len(text_sequences)

214682

# Keras

### Keras Tokenization

#### import Tokenizer from Keras...

In [24]:
#!pip uninstall tensorflow
#!pip install tensorflow==2.12.0
import tensorflow as tf
import keras
from keras.preprocessing.text import Tokenizer

In [25]:
# integer encode sequences of words
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)
sequences = tokenizer.texts_to_sequences(text_sequences)

#### List the sequences[0]

In [26]:
sequences[0]

[158,
 9443,
 17526,
 402,
 42,
 1043,
 43,
 247,
 659,
 140,
 296,
 116,
 82,
 787,
 347,
 113,
 36,
 50,
 1788,
 6,
 49,
 3028,
 3,
 218,
 442,
 5]

#### display the tokenizer.index_word

In [27]:
tokenizer.index_word

{1: 'the',
 2: 'of',
 3: 'and',
 4: 'a',
 5: 'to',
 6: 'in',
 7: 'that',
 8: 'his',
 9: 'it',
 10: 'i',
 11: 'he',
 12: 'but',
 13: "'s",
 14: 'as',
 15: 'with',
 16: 'is',
 17: 'was',
 18: 'for',
 19: 'all',
 20: 'this',
 21: 'at',
 22: 'not',
 23: 'by',
 24: 'whale',
 25: 'from',
 26: 'so',
 27: 'him',
 28: 'on',
 29: 'be',
 30: 'one',
 31: 'you',
 32: 'there',
 33: 'now',
 34: 'had',
 35: 'have',
 36: 'or',
 37: 'were',
 38: 'they',
 39: 'like',
 40: 'which',
 41: 'then',
 42: 'me',
 43: 'some',
 44: 'their',
 45: 'what',
 46: 'when',
 47: 'an',
 48: 'are',
 49: 'my',
 50: 'no',
 51: 'upon',
 52: 'out',
 53: 'man',
 54: 'into',
 55: 'ship',
 56: 'up',
 57: 'more',
 58: 'ahab',
 59: 'if',
 60: 'them',
 61: 'old',
 62: 'we',
 63: 'sea',
 64: 'would',
 65: "'",
 66: 'ye',
 67: 'do',
 68: 'other',
 69: 'been',
 70: 'over',
 71: 'these',
 72: 'will',
 73: 'though',
 74: 'only',
 75: 'its',
 76: 'down',
 77: 'such',
 78: 'who',
 79: 'yet',
 80: 'head',
 81: 'time',
 82: 'long',
 83: 'boat

#### using a for loop, for i in sequences[0], print the tokenizer.index_word

In [28]:
for i in sequences[0]:
    print(str(i) + " : " + tokenizer.index_word[i])

158 : chapter
9443 : 1
17526 : loomings
402 : call
42 : me
1043 : ishmael
43 : some
247 : years
659 : ago
140 : never
296 : mind
116 : how
82 : long
787 : precisely
347 : having
113 : little
36 : or
50 : no
1788 : money
6 : in
49 : my
3028 : purse
3 : and
218 : nothing
442 : particular
5 : to


#### print the tokenizer.word_counts

In [29]:
print(tokenizer.word_counts)

OrderedDict([('chapter', 4447), ('1', 28), ('loomings', 3), ('call', 1382), ('me', 16095), ('ishmael', 500), ('some', 15789), ('years', 2400), ('ago', 815), ('never', 5262), ('mind', 2039), ('how', 6330), ('long', 8567), ('precisely', 690), ('having', 1679), ('little', 6412), ('or', 17879), ('no', 14916), ('money', 305), ('in', 105799), ('my', 15231), ('purse', 178), ('and', 164029), ('nothing', 2936), ('particular', 1273), ('to', 117832), ('interest', 442), ('on', 26910), ('shore', 572), ('i', 53430), ('thought', 3874), ('would', 11232), ('sail', 2522), ('about', 7982), ('a', 119756), ('see', 6734), ('the', 367474), ('watery', 650), ('part', 3874), ('of', 168116), ('world', 4420), ('it', 64056), ('is', 43758), ('way', 6942), ('have', 19604), ('driving', 234), ('off', 5642), ('spleen', 26), ('regulating', 26), ('circulation', 26), ('whenever', 390), ('find', 1404), ('myself', 1716), ('growing', 234), ('grim', 286), ('mouth', 1456), ('damp', 234), ('drizzly', 26), ('november', 52), ('so

#### get the len of tokenizer.word_counts and assign it to a variable called vocabulary_size

In [30]:
vocabulary_size = len(tokenizer.word_counts)

### Convert to Numpy Matrix

In [31]:
import numpy as np

#### Create a numpy array with the seqences and call it sequences

In [32]:
sequences = np.array(sequences)

#### print the sequences

In [33]:
print(sequences)

[[  158  9443 17526 ...   218   442     5]
 [ 9443 17526   402 ...   442     5  1165]
 [17526   402    42 ...     5  1165    42]
 ...
 [  240   938   351 ...  1419  1313    74]
 [  938   351  1418 ...  1313    74   219]
 [  351  1418     3 ...    74   219   222]]


# Creating an LSTM based model

#### import keras, Sequential, Dense, LSTM, and Embedding

In [34]:
from tensorflow import keras
from tensorflow.keras.models import Sequential
from keras.layers import Dense, LSTM, Embedding

#### def a function called:  create_model(vocabulary_size, seq_len): <br> in the model add a sequential model, add (Embedding(vocabulary_size, 25, input_length=seq_len), add (LSTM(150, return_sequences=True), add (LSTM(150), add (Dense(150, activation='relu'), Dense(vocabulary_size, activation='softmax')<br> then compile the model using; loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'] <br> finally, print the summary of the model and return the model. 

In [47]:
def create_model(vocabulary_size, seq_len):
    
    # your code goes here
    model = Sequential()
    model.add(Embedding(vocabulary_size, 25, input_length=seq_len))
    model.add(LSTM(150, return_sequences=True))
    model.add(LSTM(150))
    model.add(Dense(150, activation='relu'))
    model.add(Dense(vocabulary_size, activation='softmax'))
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    model.summary()
    return model

### Train / Test Split

#### import to_categorical from from tensorflow.keras.utils 

In [48]:
from tensorflow.keras.utils import to_categorical

#### display the sequences

In [49]:
sequences

array([[  158,  9443, 17526, ...,   218,   442,     5],
       [ 9443, 17526,   402, ...,   442,     5,  1165],
       [17526,   402,    42, ...,     5,  1165,    42],
       ...,
       [  240,   938,   351, ...,  1419,  1313,    74],
       [  938,   351,  1418, ...,  1313,    74,   219],
       [  351,  1418,     3, ...,    74,   219,   222]])

#### now, display the first 49 

In [50]:
sequences[:,:-1]

array([[  158,  9443, 17526, ...,     3,   218,   442],
       [ 9443, 17526,   402, ...,   218,   442,     5],
       [17526,   402,    42, ...,   442,     5,  1165],
       ...,
       [  240,   938,   351, ...,    84,  1419,  1313],
       [  938,   351,  1418, ...,  1419,  1313,    74],
       [  351,  1418,     3, ...,  1313,    74,   219]])

#### now display the last word only

In [51]:
# last Word
sequences[:,-1]

array([   5, 1165,   42, ...,   74,  219,  222])

#### assing the sequences to the variables X, and y

In [52]:
X = sequences[:,:-1]

In [53]:
y = sequences[:,-1]

In [54]:
y = to_categorical(y, num_classes=vocabulary_size+1)

In [55]:
seq_len = X.shape[1]

In [56]:
seq_len

25

### Training the Model

#### define the model 

In [57]:
model = create_model(vocabulary_size+1, seq_len)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 25, 25)            438175    
                                                                 
 lstm (LSTM)                 (None, 25, 150)           105600    
                                                                 
 lstm_1 (LSTM)               (None, 150)               180600    
                                                                 
 dense (Dense)               (None, 150)               22650     
                                                                 
 dense_1 (Dense)             (None, 17527)             2646577   
                                                                 
Total params: 3,393,602
Trainable params: 3,393,602
Non-trainable params: 0
_________________________________________________________________


---

----

#### import dump,load from pickle 

In [58]:
from pickle import dump

In [ ]:
#### fit the model using X, y, batch_size=128, epochs=5,verbose=1

In [59]:
len(y) / 25

8587.28

In [60]:
model.fit(X, y, batch_size=128, epochs=5, verbose=1)

Epoch 1/5
1678/1678 [==============================] - 432s 254ms/step - loss: 0.0083 - accuracy: 0.0633
Epoch 2/5
1678/1678 [==============================] - 401s 239ms/step - loss: 4.6370e-04 - accuracy: 0.0641
Epoch 3/5
1678/1678 [==============================] - 390s 233ms/step - loss: 4.6661e-04 - accuracy: 0.0649
Epoch 4/5
1678/1678 [==============================] - 393s 234ms/step - loss: 4.6678e-04 - accuracy: 0.0653
Epoch 5/5
1678/1678 [==============================] - 395s 235ms/step - loss: 4.6539e-04 - accuracy: 0.0654


#### save the model to file and call it: newtext.h5

In [61]:
model.save('newtext.h5')


#### save the tokenizer

In [62]:
dump(tokenizer, open('newtext', 'wb'))

# Generating New Text

#### import: randint from random, load from pickle,  load_model from keras.models and pad_sequences

In [64]:
from random import randint
from pickle import load
from keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences

#### run this function below

In [65]:
def generate_text(model, tokenizer, seq_len, seed_text, num_gen_words):
    '''
    INPUTS:
    model : model that was trained on text data
    tokenizer : tokenizer that was fit on text data
    seq_len : length of training sequence
    seed_text : raw string text to serve as the seed
    num_gen_words : number of words to be generated by model
    '''
    
    # Final Output
    output_text = []
    
    # Intial Seed Sequence
    input_text = seed_text
    
    # Create num_gen_words
    for i in range(num_gen_words):
        
        # Take the input text string and encode it to a sequence
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        
        # Pad sequences to our trained rate (50 words in the video)
        pad_encoded = pad_sequences([encoded_text], maxlen=seq_len, truncating='pre')
        
        # Predict Class Probabilities for each word - Original
        #pred_word_ind = model.predict_classes(pad_encoded, verbose=0)[0]
        
        #good one so far: 
        pred_word_ind = (model.predict(pad_encoded) > 0.5).astype("int32")
        
        #pred_word_ind = (model.predict(pad_encoded)).astype("int32")
        #pred_word_ind = (model.predict(pad_encoded) > 0.5)
        
        # Grab word
        #pred_word = tokenizer.index_word[pred_word_ind] 
        pred_word = (tokenizer.index_word[pred_word_ind])
        
        # Update the sequence of input text (shifting one over with the new word)
        input_text += ' ' + pred_word
        
        output_text.append(pred_word)
        
    # Make it look like a sentence.
    return ' '.join(output_text)

### Grab a random seed sequence. For instance text_sequences[0]

In [66]:
import random
random.seed(101)
random_pick = random.randint(0,len(text_sequences))

In [67]:
random_seed_text = text_sequences[random_pick]

In [68]:
random_seed_text

['he',
 'recognised',
 'his',
 'cutting',
 'spade',
 'pole',
 'entangled',
 'in',
 'the',
 'lines',
 'that',
 'were',
 'knotted',
 'round',
 'the',
 'tail',
 'of',
 'one',
 'of',
 'these',
 'whales',
 'there',
 "'s",
 'a',
 'pretty',
 'fellow']

In [69]:
seed_text = ' '.join(random_seed_text)

In [70]:
seed_text

"he recognised his cutting spade pole entangled in the lines that were knotted round the tail of one of these whales there 's a pretty fellow"

### Exploring Generated Sequence

#### create a variable called full_text and read the file: moby_dick_four_chapters.txt

In [71]:
full_text = read_file('moby_dick_four_chapters.txt')

In [72]:
for i,word in enumerate(full_text.split()):
    if word == 'inkling':
        print(' '.join(full_text.split()[i-20:i+20]))
        print('\n')

were stains of some sort or other. At first I knew not what to make of this; but soon an inkling of the truth occurred to me. I remembered a story of a white man--a whaleman too--who, falling among the




#### That's the end